project-meta:
  project-name: E-Calc
  date-started: 2026-03-16
  last-updated: 2026-08-28
  languages:
    - Extended Backus-Naur Form (ISO standard)
  status: Deprecated
  license: MIT
  version: 1.0.0

build:
  dev-environments:
    - Ubuntu (WSL2)
  no-build: true

team:
  author: Ethan Kletschke
  contributors:
    - name: Ethan Kletschke
      role: Author and owner
      github-username: ethanKletschke
